// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST.HR.Domain.DAL;

namespace ST.HR.Domain.DAL.Migrations
{
    [DbContext(typeof(HrContext))]
    partial class HrContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("ST.HR.Domain.Entities.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Administrator")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseSalaryRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Group")
                        .HasColumnType("INTEGER");

                    b.Property<long>("HeadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Administrator = true,
                            BaseSalaryRate = 50.100000000000001,
                            EmploymentDate = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FullName = "Administrator",
                            Group = 2,
                            HeadId = 0L,
                            PasswordHash = "8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918",
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            Administrator = false,
                            BaseSalaryRate = 10.0,
                            EmploymentDate = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FullName = "User U. A.",
                            Group = 2,
                            HeadId = 0L,
                            PasswordHash = "F6E0A1E2AC41945A9AA7FF8A8AAA0CEBC12A3BCC981A929AD5CF810A090E11AE",
                            UserName = "user1"
                        },
                        new
                        {
                            Id = 3L,
                            Administrator = false,
                            BaseSalaryRate = 20.0,
                            EmploymentDate = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FullName = "User GU. GA.",
                            Group = 1,
                            HeadId = 2L,
                            PasswordHash = "9B871512327C09CE91DD649B3F96A63B7408EF267C8CC5710114E629730CB61F",
                            UserName = "user2"
                        },
                        new
                        {
                            Id = 4L,
                            Administrator = false,
                            BaseSalaryRate = 20.0,
                            EmploymentDate = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FullName = "User RU. RA.",
                            Group = 1,
                            HeadId = 2L,
                            PasswordHash = "556D7DC3A115356350F1F9910B1AF1AB0E312D4B3E4FC788D2DA63668F36D017",
                            UserName = "user3"
                        },
                        new
                        {
                            Id = 5L,
                            Administrator = false,
                            BaseSalaryRate = 10.0,
                            EmploymentDate = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FullName = "User With Sub Employees",
                            Group = 2,
                            HeadId = 2L,
                            PasswordHash = "3538A1EF2E113DA64249EEA7BD068B585EC7CE5DF73B2D1E319D8C9BF47EB314",
                            UserName = "user4"
                        },
                        new
                        {
                            Id = 6L,
                            Administrator = false,
                            BaseSalaryRate = 10.0,
                            EmploymentDate = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FullName = "Sub SUB Employees",
                            Group = 1,
                            HeadId = 5L,
                            PasswordHash = "91A73FD806AB2C005C13B4DC19130A884E909DEA3F72D46E30266FE1A1F588D8",
                            UserName = "user5"
                        },
                        new
                        {
                            Id = 7L,
                            Administrator = false,
                            BaseSalaryRate = 25.0,
                            EmploymentDate = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FullName = "Salesman Man Sales",
                            Group = 3,
                            HeadId = 0L,
                            PasswordHash = "C7E616822F366FB1B5E0756AF498CC11D2C0862EDCB32CA65882F622FF39DE1B",
                            UserName = "user6"
                        },
                        new
                        {
                            Id = 8L,
                            Administrator = false,
                            BaseSalaryRate = 25.0,
                            EmploymentDate = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FullName = "Salesman Sub Man Sales",
                            Group = 3,
                            HeadId = 7L,
                            PasswordHash = "C7E616822F366FB1B5E0756AF498CC11D2C0862EDCB32CA65882F622FF39DE1B",
                            UserName = "user6"
                        },
                        new
                        {
                            Id = 9L,
                            Administrator = false,
                            BaseSalaryRate = 25.0,
                            EmploymentDate = new DateTime(2020, 2, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            FullName = "Salesman Sub Man Sales",
                            Group = 3,
                            HeadId = 8L,
                            PasswordHash = "EAF89DB7108470DC3F6B23EA90618264B3E8F8B6145371667C4055E9C5CE9F52",
                            UserName = "user7"
                        });
                });

            modelBuilder.Entity("ST.HR.Domain.Entities.SalaryRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubordinateLevelMax")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SubordinatePremium")
                        .HasColumnType("REAL");

                    b.Property<double>("YearPremium")
                        .HasColumnType("REAL");

                    b.Property<double>("YearPremiumMax")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("SalaryRules");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            SubordinateLevelMax = 0,
                            SubordinatePremium = 0.0,
                            YearPremium = 3.0,
                            YearPremiumMax = 30.0
                        },
                        new
                        {
                            Id = 2L,
                            SubordinateLevelMax = 1,
                            SubordinatePremium = 0.5,
                            YearPremium = 5.0,
                            YearPremiumMax = 40.0
                        },
                        new
                        {
                            Id = 3L,
                            SubordinateLevelMax = -1,
                            SubordinatePremium = 0.29999999999999999,
                            YearPremium = 1.0,
                            YearPremiumMax = 35.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
